package ui;

public enum Communicate {
    GAME, START, RULES, HORIZONTAL, VERTICAL, CORRECT_INPUT, SYMBOL_TO_WIN, INCORRECT_CONFIG,
    CURRENT_PLAYER_TURN, WRONG_TURN, FINISH, EXIT, CREATED, FIRST_PLAYER, SECOND_PLAYER,
    START_FIRST, SYMBOL, WRONG_GLOBAL, WHO_START, DRAW, WON, TRIES
}
